name: build and test

on:
  push:
  pull_request:
    branches:
      - "*"

jobs:
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v3
      -uses: actions/setup-node@v3
      with:
        node-version: "17"
        cache: 'yarn'
      -run: yarn install --frozen-lockfile
      -run: yarn test
