name: Deploy

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: always() && (needs.build-and-test.result == 'success'
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "zombiecide-client"
          heroku_email: "hman.dahlen@gmail.com"
